spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:mysql://localhost:3306/coursework?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ld1995
    password: Ld_01482014