server:
  port: 5000

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://aa1r4kjibnjtmua.chddidqsrz8p.us-east-2.rds.amazonaws.com:3306/aa1r4kjibnjtmua?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ld1995
    password: Ld_01482014
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 3600000
